inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
  Enabled: true

