default: &default
  database: testdb
  username: postgres
  password: readyset
  adapter: postgresql
  host: "127.0.0.1"

test:
  primary:
    <<: *default
    port: 5432
  readyset:
    <<: *default
    database_tasks: false
    port: 5433

